import { imageModels } from "./models";
import type { ImageAspectRatio, ImageGeneration, ImageModelId } from "./types";
import { shopifyLogo } from "../dashboard/brand-icons";

function esc(value: string): string { return value.replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char]!); }

function resultCard(generation: ImageGeneration, url: string, index: number): string {
  return `<article class="generated-card" data-generation-id="${esc(generation.id)}"><img src="${esc(url)}" alt="Résultat ${index + 1} pour ${esc(generation.prompt)}" loading="lazy"><div class="image-actions"><a href="${esc(url)}" download target="_blank">Télécharger</a><button data-image-command="reference" data-image-url="${esc(url)}">Comme référence</button><button data-image-command="variation" data-image-url="${esc(url)}">Créer une variation</button><button class="accent" data-image-command="insert" data-image-url="${esc(url)}">Ajouter à une page</button></div></article>`;
}

export function renderStudioView(input: { workspaceName: string; generations: ImageGeneration[]; pending?: { prompt: string; model: ImageModelId; aspectRatio: ImageAspectRatio; numImages: number } | null }): string {
  const latest = input.generations[0];
  const images = input.generations.flatMap((generation) => generation.images.map((image, index) => resultCard(generation, image.url, index))).join("");
  const history = input.generations.map((generation) => `<button data-history-id="${esc(generation.id)}"><span>${generation.images[0] ? `<img src="${esc(generation.images[0].url)}" alt="">` : "✦"}</span><span><strong>${esc(generation.prompt)}</strong><small>${esc(imageModels().find((item) => item.id === generation.model)?.label ?? generation.model)} · ${esc(generation.aspectRatio)}</small></span></button>`).join("");
  const active = input.pending;
  const pending = active ? Array.from({ length: active.numImages }, (_, index) => `<article class="pending-image-frame" data-generation-pending style="aspect-ratio:${esc(active.aspectRatio.replace(":", "/"))}"><div class="pending-image-glow"></div><div class="pending-image-spinner" aria-hidden="true"></div><div class="pending-image-copy"><span>Génération en cours</span><strong>${esc(active.prompt)}</strong><small>${esc(imageModels().find((item) => item.id === active.model)?.label ?? active.model)} · image ${index + 1}/${active.numImages}</small></div></article>`).join("") : "";
  const pendingHistory = input.pending ? `<button class="is-generating"><span class="mini-spinner"></span><span><strong>${esc(input.pending.prompt)}</strong><small>Génération en cours…</small></span></button>` : "";
  return `<div class="studio-shell"><aside class="studio-history"><a class="studio-brand" href="/dashboard">weflo<span>.</span></a><a class="back-link" href="/dashboard">← Retour à l’espace</a><button class="new-session" data-new-session>＋ Nouvelle création</button><p class="side-title">HISTORIQUE</p><div data-studio-history>${pendingHistory}${history || (!input.pending ? `<p class="empty-history">Tes générations apparaîtront ici.</p>` : "")}</div><nav><a href="/creations">▣ Mes créations</a><a href="/boutique">${shopifyLogo()} Ma boutique</a></nav></aside>
    <main class="studio-canvas"><header><div><p class="eyebrow">STUDIO IMAGES</p><h1>Imagine. Génère. Vends.</h1></div><span>${esc(input.workspaceName)}</span></header><section class="result-grid" data-result-grid>${pending}${images || (!input.pending ? `<div class="studio-empty"><span>✦</span><h2>Ton prochain visuel commence par une idée.</h2><p>Décris une scène, ajoute ton produit en référence et choisis le modèle adapté.</p><div><button data-prompt-example="Photo e-commerce premium du produit, lumière naturelle et fond éditorial">Photo produit premium</button><button data-prompt-example="Publicité Meta avec une accroche courte et lisible, produit parfaitement fidèle">Static Meta avec texte</button><button data-prompt-example="Le produit dans une vraie scène de vie, composition crédible et élégante">Lifestyle réaliste</button></div></div>` : "")}</section>
      <form class="studio-composer" data-studio-form><div class="reference-preview" data-reference-preview hidden><img alt="Produit de référence"><button type="button" data-reference-remove aria-label="Retirer la référence">×</button></div><textarea name="prompt" placeholder="Décris l’image que tu veux créer…" aria-label="Prompt de génération">${latest ? "" : ""}</textarea><div class="composer-row"><label class="attach">＋ Image de référence<input type="file" accept="image/png,image/jpeg,image/webp" data-reference-input hidden></label><span class="product-lock">◉ Fidélité produit renforcée</span><button type="submit">Générer <span>↗</span></button></div></form>
    </main><aside class="studio-settings"><header><strong>Direction artistique</strong><small>Chaque réglage reste modifiable.</small></header><section><p>MODÈLE</p><div class="model-list">${imageModels().map((model, index) => `<button class="${index === 0 ? "is-active" : ""}" data-model="${model.id}"><span>✦</span><span><strong>${model.label}</strong><small>${model.description}</small></span><i>${index === 0 ? "Rapide" : "Pro"}</i></button>`).join("")}</div></section><section><p>FORMAT</p><div class="ratio-list">${["1:1", "4:3", "16:9", "3:4", "9:16"].map((ratio, index) => `<button class="${index === 0 ? "is-active" : ""}" data-ratio="${ratio}"><i style="aspect-ratio:${ratio.replace(":", "/")}"></i><span>${ratio}</span></button>`).join("")}</div></section><section><p>VARIANTES</p><div class="count-list">${[1,2,3,4].map((n) => `<button class="${n === 1 ? "is-active" : ""}" data-count="${n}">${n}</button>`).join("")}</div></section><div class="studio-tip"><strong>Conseil Weflo</strong><p>Ajoute une photo nette du produit pour garder sa forme, ses matières et ses détails.</p></div></aside></div><dialog class="insert-dialog" data-insert-dialog><button data-insert-close aria-label="Fermer">×</button><p class="eyebrow">UTILISER LE VISUEL</p><h2>Ajouter à une page</h2><p>Choisis la création à ouvrir. Le visuel t’attendra dans l’éditeur.</p><div data-page-choices></div></dialog>`;
}
