import type { ThemeFile } from "./adapters/types";

export const wefloThemeShell: ThemeFile[] = [
  { key: "layout/theme.liquid", value: `<!doctype html><html lang="{{ request.locale.iso_code }}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="preconnect" href="https://cdn.shopify.com" crossorigin><link rel="stylesheet" href="{{ 'weflo-base.css' | asset_url }}"><link rel="stylesheet" href="{{ 'weflo-profile.css' | asset_url }}">{{ content_for_header }}</head><body class="weflo-theme">{% sections 'header-group' %}<main id="MainContent" role="main">{{ content_for_layout }}</main>{% sections 'footer-group' %}<script src="{{ 'weflo-product-form.js' | asset_url }}" defer="defer"></script></body></html>` },
  { key: "config/settings_schema.json", value: JSON.stringify([{ name: "Weflo", settings: [{ type: "color", id: "weflo_background", label: "Arrière-plan", default: "#ffffff" }, { type: "color", id: "weflo_ink", label: "Texte", default: "#111111" }] }], null, 2) },
  { key: "config/settings_data.json", value: JSON.stringify({ current: "Default", presets: { Default: { weflo_background: "#ffffff", weflo_ink: "#111111" } } }, null, 2) },
  { key: "locales/fr.default.json", value: JSON.stringify({ general: { add_to_cart: "Ajouter au panier", sold_out: "Indisponible", quantity: "Quantité" } }, null, 2) },
  { key: "locales/en.default.json", value: JSON.stringify({ general: { add_to_cart: "Add to cart", sold_out: "Sold out", quantity: "Quantity" } }, null, 2) },
  { key: "assets/weflo-base.css", value: `:root{--wf-background:{{ settings.weflo_background | default: '#ffffff' }};--wf-surface:#fff;--wf-ink:{{ settings.weflo_ink | default: '#111111' }}}*{box-sizing:border-box}body{margin:0;background:var(--wf-background);color:var(--wf-ink);font-family:system-ui,sans-serif}.weflo-theme a{color:inherit}.weflo-theme button,.weflo-theme input,.weflo-theme select{font:inherit}.wf-section,.weflo-product-main{max-width:1240px;margin:auto;padding:clamp(42px,7vw,96px) 24px}.wf-product__form{display:grid;gap:12px;max-width:520px}.wf-product__form label{display:grid;gap:6px}.wf-product__form input,.wf-product__form select{min-height:44px;padding:8px;border:1px solid currentColor;background:transparent}.wf-product__form button{min-height:48px;padding:12px 20px;border:0;border-radius:var(--wf-profile-button-radius,8px);background:var(--wf-profile-ink,var(--wf-ink));color:var(--wf-profile-surface,var(--wf-surface));font-weight:700}.wf-product__prices{display:flex;gap:10px;font-size:1.25rem}.wf-product__quantity-offers{display:flex;gap:8px;border:0;padding:0}.wf-product__setup{padding:12px;border:1px solid currentColor;border-radius:8px}` },
  { key: "sections/weflo-header.liquid", value: `<header class="weflo-header"><a href="{{ routes.root_url }}">{{ shop.name | escape }}</a></header>{% schema %}{"name":"Weflo header","settings":[],"presets":[{"name":"Weflo header"}]}{% endschema %}` },
  { key: "sections/weflo-footer.liquid", value: `<footer class="weflo-footer"><small>{{ shop.name | escape }}</small></footer>{% schema %}{"name":"Weflo footer","settings":[],"presets":[{"name":"Weflo footer"}]}{% endschema %}` },
  { key: "sections/weflo-page-shell.liquid", value: `<section class="wf-section"><h1>{{ page.title | default: shop.name | escape }}</h1></section>{% schema %}{"name":"Weflo page shell","settings":[],"presets":[{"name":"Weflo page shell"}]}{% endschema %}` },
  { key: "sections/header-group.json", value: JSON.stringify({ sections: { header: { type: "weflo-header", settings: {} } }, order: ["header"] }, null, 2) },
  { key: "sections/footer-group.json", value: JSON.stringify({ sections: { footer: { type: "weflo-footer", settings: {} } }, order: ["footer"] }, null, 2) },
];
