import { shopifyLogo } from "./brand-icons";

export type BoutiqueViewInput = { workspaceName: string; workspaceId: string; status: "none" | "connected" | "invalid"; shopDomain: string | null };
function esc(value: string): string { return value.replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char]!); }

export function renderBoutiqueView(input: BoutiqueViewInput): string {
  const connected = input.status === "connected";
  const title = connected ? "Boutique connectée" : input.status === "invalid" ? "Connexion à vérifier" : "Connecte ta boutique Shopify";
  return `<div class="boutique-shell"><aside><a class="wordmark" href="/dashboard">weflo<span>.</span></a><nav><a href="/dashboard">⌂ Accueil</a><a href="/creations">▣ Mes créations</a><a href="/studio">✦ Studio images</a><a class="is-active" href="/boutique">${shopifyLogo()} Ma boutique</a><a href="/facturation">◈ Abonnement</a></nav></aside><main><header><div><p class="eyebrow">SHOPIFY</p><h1>Ma boutique</h1><p>Publie tes pages Weflo dans le thème Shopify de ton choix.</p></div><a href="/creations">Voir mes créations →</a></header><section class="connection-card status-${input.status}"><div class="shopify-hero">${shopifyLogo("full")}</div><div><span class="status-pill">${connected ? "● Connectée" : input.status === "invalid" ? "● Action requise" : "● Non connectée"}</span><h2>${title}</h2><p>${connected ? `Les sections Weflo peuvent être publiées sur <strong>${esc(input.shopDomain ?? "")}</strong>. Le thème est choisi uniquement au moment de publier.` : "Connecte une boutique de développement ou ta boutique principale. Weflo ne publie rien sans ta confirmation."}</p>${connected ? `<div class="connected-actions"><a href="/creations">Choisir une page à publier</a><button data-shopify-disconnect>Déconnecter</button></div>` : `<form data-shopify-form><input type="hidden" name="workspaceId" value="${esc(input.workspaceId)}"><label>Domaine Shopify<input name="shopDomain" placeholder="ma-boutique.myshopify.com" value="${esc(input.shopDomain ?? "")}" required></label><label>Jeton d’accès Admin<input name="token" type="password" placeholder="shpat_••••••••" autocomplete="off" required></label><button type="submit">Connecter Shopify</button><p data-shopify-error hidden></p></form>`}</div></section><section class="shopify-steps"><article><span>01</span><h3>Connecte</h3><p>Le catalogue et les thèmes disponibles restent dans ton espace.</p></article><article><span>02</span><h3>Crée</h3><p>Weflo construit de vraies sections éditables, pas une capture aplatie.</p></article><article><span>03</span><h3>Choisis le thème</h3><p>Actif, copie du thème actif ou nouveau thème Weflo au moment de publier.</p></article></section><section class="theme-note"><div><p class="eyebrow">PUBLICATION SÛRE</p><h2>Ton thème reste sous ton contrôle.</h2></div><ul><li>Prévisualisation avant publication</li><li>Confirmation explicite pour le thème actif</li><li>Sections Liquid et réglages Shopify modifiables</li></ul></section></main></div>`;
}
