import { premiumPack } from "./pack-factory";

export const advertorialPacks = [
  premiumPack({ type: "advertorialMasthead", name: "Masthead advertorial", category: "content", family: "advertorial", tags: ["advertorial", "ouverture", "éditorial"], layout: "editorial", variants: [["journal", "Journal", "Titre et média de magazine."], ["reportage", "Reportage", "Ouverture factuelle avec contexte."], ["opinion", "Chronique", "Angle signé et personnel."]] }),
  premiumPack({ type: "authorLine", name: "Ligne d’auteur", category: "content", family: "advertorial", tags: ["advertorial", "auteur"], variants: [["byline", "Signature", "Une ligne d’auteur minimaliste."], ["profile", "Profil", "Auteur accompagné d’un bloc de contexte."], ["expert", "Expert", "Signature soutenue par une qualification."]] }),
  premiumPack({ type: "editorialBody", name: "Corps éditorial", category: "content", family: "advertorial", tags: ["advertorial", "article", "chapitre"], layout: "editorial", variants: [["longform", "Long format", "Colonne de lecture continue."], ["chaptered", "Chapitres", "Lecture séquencée en épisodes."], ["scannable", "Scannable", "Paragraphes courts et points clés."]] }),
  premiumPack({ type: "evidenceCallout", name: "Encadré de preuve", category: "content", family: "advertorial", tags: ["preuve", "source", "advertorial"], variants: [["citation", "Citation", "Une preuve isolée dans un encadré."], ["data", "Données", "Preuve organisée en chiffres et notes."], ["expert-note", "Note d’expert", "Observation contextualisée par un spécialiste."]] }),
  premiumPack({ type: "inlineProduct", name: "Produit intégré", category: "commerce", family: "advertorial", tags: ["produit", "advertorial", "achat"], capabilities: ["product-form", "variant-selection"], layout: "product", variants: [["compact", "Compact", "Produit présenté au fil de la lecture."], ["feature", "Produit vedette", "Carte produit plus expressive dans l’article."], ["offer", "Offre éditoriale", "Produit et bénéfice réunis dans un encadré."]] }),
  premiumPack({ type: "conversionClose", name: "Conclusion conversion", category: "conversion", family: "conversion-capture", tags: ["cta", "conversion", "conclusion"], variants: [["final-cta", "CTA final", "Clôture simple avec une action unique."], ["offer-stack", "Pile d’offre", "Réassurance et action regroupées."], ["decision", "Aide à la décision", "Résumé final qui répond aux dernières hésitations."]] }),
];
