import type { ArtDirectionProfile, BuyerPersona, ImportedProduct, MarketingAngle, ProductTruthSheet } from "./types";

export type StoreRecipeItem = { type: string; variant: string; purpose: string };
export type StoreRecipe = { id: string; profileId: ArtDirectionProfile["id"]; sections: StoreRecipeItem[] };

type RecipeInput = { product: ImportedProduct; truth: ProductTruthSheet; artDirection: ArtDirectionProfile; personas: BuyerPersona[]; angles: MarketingAngle[] };
const section = (type: string, variant: string, purpose: string): StoreRecipeItem => ({ type, variant, purpose });

export function buildStoreRecipe(input: RecipeInput): StoreRecipe {
  const proof = input.product.reviews.length ? "reviews" : "testimonials";
  const schemes: Record<ArtDirectionProfile["id"], StoreRecipeItem[]> = {
    "warm-home": [section("announcement","quiet-trust","Rassurer"),section("navigation","editorial","Installer la marque"),section("productHero","ambient-editorial","Projeter dans un intérieur"),section("gallery","lifestyle-grid","Montrer les ambiances"),section("productMain","calm-buy-box","Faciliter l’achat"),section("imageText","room-story","Raconter l’usage"),section("benefits","material-cards","Expliquer les bénéfices"),section(proof,"home-stories","Apporter la preuve"),section("bundle","room-set","Augmenter le panier"),section("shipping","assurance-strip","Rassurer sur la commande"),section("faq","quiet-accordion","Lever les objections"),section("cta","editorial-close","Conclure"),section("footer","editorial","Signer")],
    "editorial-beauty": [section("navigation","minimal","Installer la marque"),section("productHero","beauty-split","Créer le désir"),section("benefits","ritual-strip","Promettre une routine"),section("productMain","beauty-buy-box","Convertir"),section("imageText","ingredient-story","Expliquer la formule"),section("gallery","editorial-mosaic","Montrer la texture"),section(proof,"beauty-journal","Prouver"),section("bundle","ritual-set","Augmenter le panier"),section("faq","editorial","Lever les objections"),section("cta","beauty-close","Conclure"),section("footer","minimal","Signer")],
    "clinical-wellness": [section("announcement","clinical-proof","Rassurer"),section("navigation","clinical","Installer la marque"),section("productHero","clinical-evidence","Clarifier la promesse"),section("productMain","clinical-buy-box","Convertir"),section("benefits","evidence-grid","Détailler les bénéfices"),section("imageText","formula-focus","Expliquer"),section(proof,"measured-proof","Prouver"),section("bundle","protocol","Structurer la cure"),section("shipping","assurance-strip","Réduire le risque"),section("faq","clinical","Lever les objections"),section("cta","clinical-close","Conclure"),section("footer","clinical","Signer")],
    "technical-performance": [section("navigation","technical","Installer la marque"),section("productHero","spec-led","Démontrer"),section("productMain","technical-buy-box","Convertir"),section("benefits","spec-grid","Expliquer les performances"),section("comparison","benchmark","Comparer"),section("gallery","detail-grid","Montrer les détails"),section(proof,"field-tests","Prouver"),section("bundle","performance-pack","Augmenter le panier"),section("shipping","service-bar","Rassurer"),section("guarantees","technical-assurance","Réduire le risque"),section("faq","technical","Lever les objections"),section("cta","performance-close","Conclure"),section("footer","technical","Signer")],
    "direct-response": [section("announcement","benefit-bar","Capter"),section("navigation","compact","Orienter"),section("productHero","problem-solution","Nommer le problème"),section("benefits","outcome-stack","Montrer la transformation"),section("productMain","conversion-buy-box","Convertir"),section("comparison","before-after","Faire comparer"),section(proof,"results-wall","Prouver"),section("bundle","best-value","Augmenter le panier"),section("guarantees","risk-reversal","Réduire le risque"),section("faq","objection-led","Lever les objections"),section("cta","direct-close","Conclure"),section("footer","compact","Signer")],
    "playful-gifting": [section("announcement","gift-note","Capter"),section("navigation","playful","Installer la marque"),section("productHero","giftable-story","Créer l’envie d’offrir"),section("gallery","color-pop","Montrer le produit"),section("productMain","gift-buy-box","Convertir"),section("benefits","occasion-cards","Donner des occasions"),section(proof,"community-grid","Prouver"),section("bundle","gift-sets","Augmenter le panier"),section("faq","friendly","Lever les objections"),section("cta","gift-close","Conclure"),section("footer","playful","Signer")],
    "premium-accessories": [section("navigation","luxury","Installer la marque"),section("productHero","object-editorial","Créer le désir"),section("gallery","lookbook","Montrer le savoir-faire"),section("productMain","luxury-buy-box","Convertir"),section("imageText","craft-story","Raconter le détail"),section("benefits","detail-led","Justifier la valeur"),section(proof,"press-quotes","Prouver"),section("bundle","curated-set","Augmenter le panier"),section("guarantees","concierge","Rassurer"),section("faq","minimal","Lever les objections"),section("cta","luxury-close","Conclure"),section("footer","luxury","Signer")],
    "food-craft": [section("announcement","origin-note","Capter"),section("navigation","craft","Installer la marque"),section("productHero","maker-led","Créer l’appétit"),section("productMain","tasting-buy-box","Convertir"),section("imageText","origin-story","Raconter la provenance"),section("benefits","tasting-notes","Expliquer"),section("gallery","table-mosaic","Montrer les usages"),section(proof,"community-table","Prouver"),section("bundle","discovery-box","Augmenter le panier"),section("faq","craft","Lever les objections"),section("cta","tasting-close","Conclure"),section("footer","craft","Signer")],
  };
  return { id: `recipe-${input.artDirection.id}`, profileId: input.artDirection.id, sections: schemes[input.artDirection.id] };
}
