import "./brand-media";
import "./commerce";
import "./conversion";
import { registerSection } from "./registry";
import { spacerSection } from "./spacer";
import { dividerSection } from "./divider";
import { customCodeSection } from "./custom-code";
import { productPacks } from "./packs/product-packs";
import { offerPacks } from "./packs/offer-packs";
import { quantityOfferSection } from "./quantity-offer";
import { proofPacks } from "./packs/proof-packs";
import { discoveryPacks } from "./packs/discovery-packs";
import { advertorialPacks } from "./packs/advertorial-packs";
import { listiclePacks } from "./packs/listicle-packs";
import { quizPacks } from "./packs/quiz-packs";
import { brandStoryPacks } from "./packs/brand-story-packs";
registerSection(spacerSection);
registerSection(dividerSection);
registerSection(customCodeSection);
for (const pack of [...productPacks, quantityOfferSection, ...offerPacks, ...proofPacks, ...discoveryPacks, ...advertorialPacks, ...listiclePacks, ...quizPacks, ...brandStoryPacks]) registerSection(pack);
export { getSectionDefinition, getSectionPack, listSectionDefinitions, listSectionPacks, normalizeSectionPack } from "./registry";
export type { SectionCapability, SectionFamily, SectionPackDefinition, SectionVariantDefinition } from "./types";
